;extension=mongodb.so
;extension=grpc.so
extension=apcu.so

; POST_MAX_SIZE (required) is taken from environment, php default is 8M
post_max_size = ${POST_MAX_SIZE:-1M}

; UPLOAD_MAX_FILESIZE (required) is taken from environment, php default is 2M
upload_max_filesize = ${UPLOAD_MAX_FILESIZE:-1M}

; MAX_FILE_UPLOADS (required) is taken from environment, php default is 20
max_file_uploads = ${MAX_FILE_UPLOADS:-1}

; MAX_INPUT_TIME (required) is taken from environment, php default is -1 ( no limits ).
; This value should theoretically be equal to the numeric value of post_max_size,
; assuming a very slow connection speed of 1 MByte/s (8 Mbit/s)
max_input_time = ${MAX_INPUT_TIME:-10}

; MAX_EXECUTION_TIME (required) is taken from environment, php default is 30
max_execution_time = ${MAX_EXECUTION_TIME:-60}

display_errors = ${DISPLAY_ERRORS:-0}
